name: pyepidisplay
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - pandas
  - pyreadr
  - pytest
  - pip
  - scikit-learn
  - r-base
  - rpy2
  - statsmodels
